start_beego: 
  defaultBuilder:
    languages:
      - go1.8
    steps:
      - run: go mod tidy
          path: ./code
      - run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go
          path: ./code